-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 16:57:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserName`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserName` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserName` (
  `user_name_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_name_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserLogin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserLogin` (
  `user_login_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_password` VARCHAR(60) NOT NULL,
  `user_name_id` INT NOT NULL,
  PRIMARY KEY (`user_login_id`),
  INDEX `fk_Users Login_User Names1_idx` (`user_name_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users Login_User Names1`
    FOREIGN KEY (`user_name_id`)
    REFERENCES `mydb`.`UserName` (`user_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AccountType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AccountType` (
  `account_type_id` INT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AccountStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AccountStatus` (
  `account_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AccountNumber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AccountNumber` (
  `account_number_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`account_number_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(15,2) NOT NULL,
  `account_type_id` INT NOT NULL,
  `account_status_id` INT UNSIGNED NOT NULL,
  `account_number_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_Accounts_Account Type1_idx` (`account_type_id` ASC) VISIBLE,
  INDEX `fk_Accounts_Account Status Type1_idx` (`account_status_id` ASC) VISIBLE,
  INDEX `fk_Accounts_Account Numbers1_idx` (`account_number_id` ASC) VISIBLE,
  CONSTRAINT `fk_Accounts_Account Type1`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `mydb`.`AccountType` (`account_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_Account Status Type1`
    FOREIGN KEY (`account_status_id`)
    REFERENCES `mydb`.`AccountStatus` (`account_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_Account Numbers1`
    FOREIGN KEY (`account_number_id`)
    REFERENCES `mydb`.`AccountNumber` (`account_number_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TransactionType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TransactionType` (
  `transaction_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_name` VARCHAR(20) NOT NULL,
  `fee_amount` DECIMAL(5,2) NOT NULL,
  `transaction_description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`transaction_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TransactionLog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TransactionLog` (
  `transaction_log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NOT NULL,
  `transaction_amount` DECIMAL(15,2) NOT NULL,
  `new_balance` DECIMAL(15,2) NOT NULL,
  `employee_id` INT UNSIGNED NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `transaction_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`transaction_log_id`),
  INDEX `fk_Transactions Log_Employee1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_Transactions Log_Accounts1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Transactions Log_Transaction Type1_idx` (`transaction_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions Log_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions Log_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions Log_Transaction Type1`
    FOREIGN KEY (`transaction_type_id`)
    REFERENCES `mydb`.`TransactionType` (`transaction_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Loan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `loan_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(15,2) NOT NULL,
  `rate` DECIMAL(5,2) NOT NULL,
  `returned_amount` DECIMAL(15,2) NULL,
  `from_date` DATETIME NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `fk_Loans_Accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Loans_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CardNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CardNumber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CardNumber` (
  `card_number_id` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`card_number_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CardType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CardType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CardType` (
  `card_type_id` INT NOT NULL AUTO_INCREMENT,
  `card_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`card_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Card` (
  `card_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_date` DATE NOT NULL,
  `exp_date` DATE NOT NULL,
  `security_number` VARCHAR(5) NOT NULL,
  `card_number_id` INT NOT NULL,
  `card_type_id` INT NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `fk_Cards_Card Numbers1_idx` (`card_number_id` ASC) VISIBLE,
  INDEX `fk_Cards_Cards Type1_idx` (`card_type_id` ASC) VISIBLE,
  INDEX `fk_Cards_Accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cards_Card Numbers1`
    FOREIGN KEY (`card_number_id`)
    REFERENCES `mydb`.`CardNumber` (`card_number_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cards_Cards Type1`
    FOREIGN KEY (`card_type_id`)
    REFERENCES `mydb`.`CardType` (`card_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cards_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FixedTermDeposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FixedTermDeposit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FixedTermDeposit` (
  `fixed_term_deposit_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(15,2) NOT NULL,
  `rate` DECIMAL(5,2) NOT NULL,
  `from_date` DATE NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`fixed_term_deposit_id`),
  INDEX `fk_Fixed-term Deposits_Accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Fixed-term Deposits_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(30) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserSecurityQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserSecurityQuestion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserSecurityQuestion` (
  `user_security_question_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_security_question` VARCHAR(45) NOT NULL,
  `user_login_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_security_question_id`),
  INDEX `fk_Users Security Questions_Users Login1_idx` (`user_login_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users Security Questions_Users Login1`
    FOREIGN KEY (`user_login_id`)
    REFERENCES `mydb`.`UserLogin` (`user_login_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserSecurityAnswer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserSecurityAnswer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserSecurityAnswer` (
  `user_security_answer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_security_answer` VARCHAR(25) NOT NULL,
  `user_security_question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_security_answer_id`),
  INDEX `fk_Users Security Answer_Users Security Questions1_idx` (`user_security_question_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users Security Answer_Users Security Questions1`
    FOREIGN KEY (`user_security_question_id`)
    REFERENCES `mydb`.`UserSecurityQuestion` (`user_security_question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FailedTransactionErrorType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FailedTransactionErrorType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FailedTransactionErrorType` (
  `failed_transaction_error_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `error_description` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`failed_transaction_error_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FailedTransactionLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FailedTransactionLog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FailedTransactionLog` (
  `failed_transaction_log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `failed_transaction_time` DATETIME NOT NULL,
  `failed_transaction_error_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`failed_transaction_log_id`),
  INDEX `fk_Failed Transaction Log_Failed Transaction Type_idx` (`failed_transaction_error_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Failed Transaction Log_Failed Transaction Type`
    FOREIGN KEY (`failed_transaction_error_type_id`)
    REFERENCES `mydb`.`FailedTransactionErrorType` (`failed_transaction_error_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CustomerAccount` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CustomerAccount` (
  `customer_account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  INDEX `fk_Customers_has_Accounts_Accounts1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Customers_has_Accounts_Customers1_idx` (`customer_id` ASC) VISIBLE,
  PRIMARY KEY (`customer_account_id`),
  CONSTRAINT `fk_Customers_has_Accounts_Customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Accounts_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountUserLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AccountUserLogin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AccountUserLogin` (
  `account_user_login_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `user_login_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`account_user_login_id`),
  INDEX `fk_Accounts_has_Users Login_Users Login1_idx` (`user_login_id` ASC) VISIBLE,
  INDEX `fk_Accounts_has_Users Login_Accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Accounts_has_Users Login_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_has_Users Login_Users Login1`
    FOREIGN KEY (`user_login_id`)
    REFERENCES `mydb`.`UserLogin` (`user_login_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
